# The URL the site will be built for
base_url = "https://tims-ev.de"
theme = "xuan"
title = "TIMs e.V."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

default_theme = "light"
#
# Sets theme and browser theme color.
# See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
accent_color = "#fff"
# Ditto but for the dark theme.
# If not set regular variant will be used.
accent_color_dark = "#10486eff"
